munich-quantum-toolkit/workflows

.github/workflows/reusable-cpp-linter.yml, .pre-commit-config.yaml
This PR adds the option to request a full clang-tidy run via a workflow option. This can be useful after updates of the clang-tidy version so that the whole code base can be checked once in a PR and it happens less frequently that warnings then pop up in subsequent PRs.
It also enables the `update` feature for the cpp-linter thread comment which repeatedly updates the linter comment instead of always creating a new one. This should lower the notification noise.
=> 🚸 improve cpp-linter configuration

.github/workflows/reusable-cpp-ci.yml, .github/workflows/reusable-cpp-coverage.yml, .github/workflows/reusable-python-ci.yml, .github/workflows/reusable-python-tests.yml
This PR improves how coverage data is collected and uploaded to codecov. Since we upload quite a couple of reports, the codecov CI was frequently failing, especially on PRs from forks.
This PR changes the workflows so that they first upload all Python coverage reports as artifacts, which are then collected and uploaded in one go.
Furthermore, this PR switches to using OIDC instead of `CODECOV_TOKEN` which eliminates the need for storing the codecov token as a repository secret.
An added benefit of this approach is that there is only one Python coverage upload; independent from the number of jobs and Python versions. Thus, the same coverage configuration can be used in all projects.
Before merging, this PR needs testing in at least one of the upstream repositories.
=> 🚸 improve coverage data collection

.github/workflows/reusable-mqt-core-update.yml
This PR adds a reusable workflow for automatically updating a FetchContent-managed mqt-core dependency.
The workflow assumes
- that there is a `cmake/ExternalDependencies.cmake` file
- that file contains (an adaptation of) the following lines
```cmake
set(MQT_CORE_VERSION 2.5.1
CACHE STRING "MQT Core version")
set(MQT_CORE_REV "0e4ff9e0521886449027b252c65913e1afa863b0"
CACHE STRING "MQT Core identifier (tag, branch or commit hash)")
```
Note that the `# cmake-format: off` and `# cmake-format: on` are required to have the version and tag appear on the same line.
It will check the latest release version (and the corresponding commit SHA) from GitHub and do a SemVer comparison with the version extracted from the CMake file.
If the version is newer or it's the same but the SHA is different, …
=> ✨ add reusable mqt-core update workflow

.github/workflows/reusable-mqt-core-update.yml
This PR adapts the reusable auto-update workflow for mqt-core to require a token for creating the update PR.
Ideally, this token is a Personal Access Token with `repo` scope because this allows the creation of the PR to also trigger corresponding `on: pull request` workflows in the PR.
Alternatively, the regular `{{ github.token }}` can be used, which still allows to create PRs, but workflows will not be run automatically for the created PR.
In order to still run workflows for such PRs, the PR can be manually closed and re-opened, which explicitly triggers the workflow runs.
=> 💥 require token for creating pull requests in auto update

.editorconfig, .github/workflows/reusable-mqt-core-update.yml
This PR first and foremost reverts the token parameter and defaults to the GitHub token for posting the potential PR. Simply closing and re-opening these PRs is not a dealbreaker.
Furthermore, it implements optional updates to the latest commit on the main branch.
Fixes #7
=> ✨ QoL improvements for MQT Core autoupdate

.github/workflows/reusable-python-packaging.yml
This PR speeds up the packaging builds (wheel + sdist) for pure Python projects by making use of `uv` as an installer when calling `build`.
=> ⚡📦 use `uv` for packaging builds in pure Python projects

.github/workflows/reusable-cpp-linter.yml
This PR allows the optional configuration of the cpp-linter `extra-args`.
This allows, e.g., to use the linter for C-based projects by setting the extra-args to `""`.
The default remains `-std=c++17` in order to require no changes for existing projects.
=> 🚸 allow configuration of the cpp-linter `extra-args`

.github/workflows/reusable-python-ci.yml
This PR allows skipping the testing pipeline on the latest supported Python version.
Under Linux, this will simply not test under that version, but all other supported versions.
Under macOS and Windows, it will test on the minimal supported version and the second latest version supported.
This is especially helpful when new Python versions are released and the ecosystem takes some time to settle and provide wheels for the new version.
The intention would be to enable the `skip-testing-latest-python` flag once a new Python version is released to get our own wheel builds out as soon as possible.
Ideally immediately after that, a follow-up PR (along with a tracking issue) can be created that disables the flag again and that helps to keep track of the progress towards fully supporting new …
=> ✨ allow skipping testing on latest Python

.github/workflows/reusable-mqt-core-update.yml
This small PR fixes an issue where the `semver` command couldn't be found when running the MQT Core update action.
I suppose this is due to `/usr/local/bin` not being on the `PATH` on GitHub action runners.
=> 🩹 fix path to `semver` in MQT Core update workflow

.github/workflows/reusable-python-packaging.yml
Instead of `3 * |supported python versions|` jobs, this will only create `3` jobs to build wheels on platforms that need emulation. Tools running this workflow and are using scikit-build-core as a build backend, should set
```toml
[tool.scikit-build]
build-dir = "build/{build_type}"
```
so that the build directory can be reused across builds. This only requires the actual binding target to be recompiled.
There is a very slim chance that this needs to be reverted or refactored if it turns out that the MQT QMAP builds exceed the six hour GitHub limit.
Tools should also set
```toml
[tool.cibuildwheel.windows]
environment = { SKBUILD_CMAKE_ARGS="--fresh" }
```
to avoid problems with old link settings remaining in the CMake cache on Windows.
=> ♻️ combine builds for emulated wheels

.github/workflows/update-major-minor-tag.yml
This PR introduces a workflow for maintaining moving minor version tags.
This should reduce the frequency in which consumers of these workflows have to update.
On the other hand, it also mandates that patch releases do not break consumers.
Adapted from https://github.com/pypa/cibuildwheel/blob/main/.github/workflows/update-major-minor-tag.yml
Fixes #14
=> ✨ moving minor tags for workflows

.github/workflows/reusable-mqt-core-update.yml
This PR adds a small note to the MQT Core Update workflows PR description explaining that the workflow can't trigger CI on its own and needs a little help.
=> 📝 add note in MQT Core Update PR description

.github/workflows/reusable-python-packaging.yml
A quick follow up to #22 that fixes an oversight in the workflow configuration.
=> 🩹 fix emulation wheel build precondition

.github/workflows/reusable-mqt-core-update.yml
The semver tool that is downloaded by this workflow does not provide the option `-i`.
Instead, the equivalent command is `semver bump patch <version>`
Before this pull request, updating the version using this workflow will fail, as `-i` is not recognised. This pull request should fix the issue.
=> fix: :bug: Fix incorrect usage of semver tool

.github/workflows/reusable-code-ql-cpp.yml, .github/workflows/reusable-cpp-coverage.yml, .github/workflows/reusable-cpp-linter.yml, .github/workflows/reusable-cpp-tests-macos.yml, .github/workflows/reusable-cpp-tests-ubuntu.yml, .github/workflows/reusable-cpp-tests-windows.yml, .github/workflows/reusable-python-ci.yml, .github/workflows/reusable-python-linter.yml, .github/workflows/reusable-python-packaging.yml, .github/workflows/reusable-python-tests.yml
With the recent update to the `setup-z3` action (https://github.com/cda-tum/setup-z3/releases/tag/v1.6.0), explicitly setting the GitHub token to use is no longer necessary.
=> 🚸 no longer need to explicitly provide `GITHUB_TOKEN` to `setup-z3`

.github/workflows/reusable-python-ci.yml, .github/workflows/reusable-python-tests.yml
This PR refactors the way tests on Python are distributed and run. Instead of running separate sessions for each Python version, this PR changes the workflows to run all sessions in a single workflow run per operating system.
This should allow for maximum caching reuse across builds and reduce the number of CI runners that need to be waited for.
It also reduces the number of macOS runners requested per CI run, which is now fixed to 2 for the python tests regardless of the number of supported Python versions.
While, previously, only the `ubuntu-latest` runner would run tests on all Python versions, this PR changes the workflows so that also macOS and Windows runners test all the versions.
This should not cause a noticable runtime increase given the excessive caching opportunities, both via …
=> ♻️ unify Python testing

.github/workflows/reusable-python-packaging.yml
This PR adds a `build-emulated-wheels` option to the `reusable-python-packaging` workflow that defaults to `true` and controls whether the emulated wheel builds are triggered.
Given that these builds take quite a while, it might be wise to turn them off for continuous deployments, e.g., from every push to main.
=> 🔧 allow to disable emulated wheel build

.github/workflows/reusable-change-detection.yml
This PR adds another output to the `reusable-change-detection` workflow that indicates whether continuous deployment should be run. The output is `true` whenever the `.github/workflows/cd.yml` file changes in a PR or when not in a PR, e.g., on pushes to main.
This allows to incorporate the CD job in the branch protection workflow and to ensure that all the jobs pass whenever the job is run as part of the CI checks on a PR.
=> ❓ add change detection for running continuous deployment

.github/workflows/reusable-python-packaging.yml
This PR adds a configuration option for turning off local versioning for `setuptools_scm`. This aids in creating development versions for TestPyPI during continuous deployment, e.g., for every push to main.
PyPI does not allow for local version fragments in version numbers when uploading packages. Thus, this option is disabled if the corresponding `no-local-version` workflow input is set to `true`.
A good default for consuming workflows is
```yaml
no-local-version: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
```
=> 🔧 add a configuration option to turn off local versioning

.github/workflows/reusable-python-packaging.yml
This PR adds custom `dev-` and `test-` prefixes to the artifacts uploaded from the `reusable-python-packaging` workflow to distinguish between the various types of uploads
- PR builds: `dev-` prefix, 
- pushes to main: `test-` prefix, and
- releases: no prefix
This is more of a cautionary measure as I believe that not distinguishing these use cases could, for example, lead to a PR overriding release artifacts.
=> 🔧 add prefixes for artifact uploads of development and test versions

.github/workflows/reusable-change-detection.yml
Another small follow-up towards enabling TestPyPI deployments. Change detection now only indicates the CD workflow to run on PRs that change the `cd.yml` workflow.
=> 🔧 only indicate a CD run on PRs that change the `cd.yml` workflow

.github/workflows/reusable-change-detection.yml
This small PR ensures that Python testing is run whenever the `uv` lock file changes.
=> 🚸 run Python tests on changes to the `uv` lock file

.github/workflows/reusable-cpp-coverage.yml, .github/workflows/reusable-python-ci.yml
This small PR ensures that the right permissions are set for the workflows handling coverage data.
When setting any kind of permission, all others default to `none`. Hence, `contents: read` needs to be set explicitly for the checkout to work.
=> 🛂 ensure right permissions for workflows

.github/workflows/reusable-cpp-coverage.yml, .github/workflows/reusable-python-ci.yml
A follow up to #46 that addresses the codecov regression reported in https://github.com/codecov/codecov-action/issues/1594.
This should just be a temporary workaround until the regression has been resolved.
After this, coverage uploads from forks should work properly again.
=> 🚑 workaround for codecov regression when using OIDC

.github/workflows/reusable-change-detection.yml
This small PR adjusts the change detection workflow to also detect Python test releated changes from project structures mostly used for pure Python projects.
=> 🔧 also detect common other Python test changes

.github/workflows/reusable-python-packaging.yml
This disables the `uv` cache for workflows where it will not be used such as the cibuildwheel runs for linux where the actual build happens in a Docker container.
This resolves CD failures seen in some of the MQT repositories.
=> 🩹 do not enable `uv` cache when it will not be used

.github/workflows/reusable-cpp-tests-macos.yml
This PR ensures that macOS C++ tests aren't aborted early upon failure.
=> 🚸 do not fail fast on macOS C++ tests

.github/workflows/reusable-python-ci.yml, .github/workflows/reusable-python-parallel-tests.yml, .github/workflows/reusable-python-tests-individual.yml
This PR adds an alternative to the existing Python testing workflow. Instead of combining minimums and regular test sessions on all Python versions into one job per platform, the new workflow maximally distributes the individual runs.
=> 🚸 Alternative workflow for running Python tests individually

.github/workflows/reusable-python-linter.yml, .github/workflows/reusable-python-packaging.yml, .github/workflows/reusable-python-tests-individual.yml, .github/workflows/reusable-python-tests.yml
The `setup-uv` action has added a way to infer the `uv` version from a respective configuration for the required uv version in the projects themselves.
The following can be placed in `pyproject.toml` to regulate the required version:
```toml
[tool.uv]
required-version = ">=0.5.20"
```
=> 🔧 do not explicitly set the `uv` version to `latest`

.github/workflows/reusable-cpp-tests-ubuntu.yml, .github/workflows/reusable-python-ci.yml, .github/workflows/reusable-python-packaging.yml
GitHub now provides free Ubuntu ARM runners: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview :tada:
This PR adds the respective runners to the C++ tests, the Python tests, as well as the Python CD configuration.
This effectively removes one of the platforms that previously required emulation (`aarch64`), which is great to see.
The new runners are enabled by default and, at the moment, I did not add a way to opt out of using them. Let's see how smooth using them turns out to be.
=> 👷 adding GitHub's new Ubuntu ARM runners to the workflows

.github/workflows/reusable-cpp-ci.yml, .github/workflows/reusable-cpp-tests-macos.yml, .github/workflows/reusable-cpp-tests-ubuntu.yml, .github/workflows/reusable-cpp-tests-windows.yml, .github/workflows/reusable-python-ci.yml, .github/workflows/reusable-python-tests-individual.yml, .github/workflows/reusable-python-tests.yml
This PR experiments with broadening the type of runners that we run CI on. 
In particular, it allows one to dynamically configure the workflow runs that should be enabled.
As a result, projects can decide on their own under which constellations they want to test.
On the C++ side, the currently available workflows are:
- (ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm, ubuntu-22.04-arm) x (gcc, clang) x (Release, Debug)
- (macos-13, macos-14, macos-15) x (clang, gcc) x (Release, Debug)
- (windows-2022, windows-2025) x (msvc, clang) x (Release, Debug)
with the following combinations being turned on by default:
- ubuntu-24.04, gcc, Release,
- ubuntu-22.04, gcc, Release,
- ubuntu-24.04-arm, gcc, Release,
- ubuntu-22.04-arm, gcc, Release,
- macos-13, clang, Release,
- macos-14, clang, Release,
- …
=> 👷🐧🍎🏁 Extensive CI testing

.github/workflows/reusable-code-ql-cpp.yml, .github/workflows/reusable-code-ql.yml, .github/workflows/reusable-cpp-ci.yml, .github/workflows/reusable-cpp-coverage.yml, .github/workflows/reusable-cpp-linter.yml, .github/workflows/reusable-python-ci.yml, .github/workflows/reusable-python-linter.yml, .github/workflows/reusable-python-packaging.yml, .github/workflows/reusable-python-tests-individual.yml, .github/workflows/reusable-python-tests.yml
This PR updates the default Z3 version used in the workflows to the latest release of Z3, which is `v4.13.4`.
=> ⬆️ update default Z3 version to `4.13.4`

.github/workflows/reusable-python-packaging.yml
This PR removes the local version handling from the Python packaging workflow.
This was mainly in place for TestPyPI uploads. 
As these have turned out to not be that useful and rather demanding on CI resources, this PR removes the corresponding handling.
This makes the workflows themselved a little cleaner with less special handling.
=> 🔥 remove local version handling

.github/workflows/reusable-python-packaging.yml
Projects can set this on their own in their `pyproject.toml`. See https://github.com/cda-tum/mqt-qmap for an example.
=> 🔥 do not force `CIBW_BEFORE_ALL` for Z3 setup on manylinux

.github/workflows/reusable-cpp-tests-ubuntu.yml
This pull request resolves a typo in the Ubuntu C++ CI configuration, which incorrectly swapped `gcc` and `clang` configurations. This fix ensures the proper setup for respective compilers during CI runs.
=> 🩹 Fix typo in CI config swapping `gcc` and `clang` on Ubuntu

.github/workflows/reusable-cpp-linter.yml
This can be helpful for MLIR-based projects where some files are only generated at build time.
=> 🚨 optionally build the project as part of the cpp-linter workflow

.github/workflows/reusable-cpp-linter.yml
This pull request refines the ignore patterns in the C++ linter workflow to exclude the `include` directory from linting checks.
Thanks @TooMuchDakka for the tip.
=> 🔧 Update ignore patterns in C++ linter workflow to include 'include' directory

.github/renovate.json5
This configures renovate to pin GitHub Actions to explicit digests in an effort to improve security given some recent precedents across the ecosystem.
=> 📌 configure pinning GitHub action digests

.github/release-drafter.yml, .github/workflows/release-drafter.yml
Simplifies the release drafter configuration to no longer relying on the auto labeler.
As a result the `pull_request_target` trigger is no longer necessary for the workflow to succeed on PRs from forks.
=> 🔧 use `pull_request` event trigger for release drafter and no more auto labeled

.github/workflows/reusable-mqt-core-update.yml
This PR adjusts the references for MQT Core now that the project has been moved to this organisation.
=> ✏️ adjust refs in MQT Core update workflow

.github/workflows/reusable-cpp-ci.yml, .github/workflows/reusable-python-ci.yml, .github/workflows/reusable-python-packaging.yml
Just yesterday, GitHub [announced](https://github.blog/changelog/2025-04-14-windows-arm64-hosted-runners-now-available-in-public-preview/) the general availability of Windows ARM runners in public preview.
This PR adds the respective runners to the C++ tests, the Python tests, as well as the Python packaging workflow.
The test workflows are currently opt-in only and will not be run by default.
The packaging workflow now includes the Windows ARM runners.
This configuration will be updated in a subsequent PR to allow opting in and out of runners for CD.
=> 👷 Add Windows 11 ARM runners

.github/workflows/reusable-cpp-tests-windows.yml, .github/workflows/reusable-python-packaging.yml, .github/workflows/reusable-python-tests.yml, .github/workflows/reusable-qiskit-upstream.yml
The `msvc-dev-cmd` does not work properly (yet) on the new Windows 11 ARM runners.
Testing over at MQT Core has shown that the action is not actually needed for our CI, so we might as well remove it.
=> 🔥 remove `msvc-dev-cmd`

.github/workflows/reusable-cpp-tests-windows.yml, CHANGELOG.md
In light of the new Windows 11 ARM runners, this PR switches from using the Ninja generator for the CI on Windows to using the MSVC generator.
=> 🔧 Use MSVC generator for Windows builds over Ninja

.github/workflows/reusable-cpp-linter.yml, CHANGELOG.md, UPGRADING.md
Previously, the `cpp` files containing the Python bindings were excluded from linting because this led to a couple of errors since the pybind11 headers were not available. The respective workflow now offers the optional setting to set up a Python environment and install pybind11. This can then be automatically caught up by the CMake configuration.
=> 🚨 Add Support for Linting Python Bindings

.github/workflows/reusable-python-linter.yml, CHANGELOG.md, UPGRADING.md
This PR adds support for running Astral's `ty` type checker as part of the `reusable-python-linter.yml` workflow.
To enable this, you can set the `run-ty` option to `true` in the workflow configuration.
Additionally, the `mypy` type checker can now be disabled by setting the `run-mypy` option to `false`.
While `ty` is a drop-in replacement for `mypy`, it is still in alpha and may not be as stable as `mypy`.
The current recommendation is to use `ty` and `mypy` in parallel, as they may catch different issues.
Once `ty` is stable, it can be used as a drop-in replacement for `mypy`.
Project may want to add `ty` to their development dependencies to ensure that the same version is used for all developers.
```commandline
uv add --dev ty
```
=> 🐍🚨 Add support for running Astral's `ty` type checker
